version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5004:5004"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
