apiVersion: batch/v1
kind: Job
metadata:
  name: deployment-success-notification
spec:
  template:
    spec:
      containers:
        - name: email-sender
          image: busybox
          command: ["/bin/sh", "-c", "echo -e 'Subject: Deployment Complete\n\nYour Kubernetes app is deployed!' | sendmail -S localhost -t"]
      restartPolicy: Never

# Step 5: Kubernetes Security Scan
  security-scan:
    name: Kubernetes Security Scan
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Install kube-bench (CIS Benchmark Scanner)
        run: |
          curl -L -o kube-bench https://github.com/aquasecurity/kube-bench/releases/tag/v0.10.1/kube-bench_0.10.1_linux_amd64.tar.gz
          chmod +x kube-bench
          sudo mv kube-bench /usr/local/bin/kube-bench

      - name: Run Kubernetes CIS Benchmark Scan
        run: kube-bench --benchmark cis-1.6   
