deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    
    steps:
      - name: Checkout Repository  # This ensures the YAML files exist
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml --validate=false
          kubectl apply -f k8s/backend-service.yaml --validate=false
          kubectl apply -f k8s/frontend-deployment.yaml --validate=false
          kubectl apply -f k8s/frontend-service.yaml --validate=false

  security-scan:
    name: Kubernetes Security Scan
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Run KubeAudit Scan
        run: |
          kubeaudit all --namespace default

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: recipient@example.com
          subject: "CI/CD Pipeline Completed"
          body: "The CI/CD pipeline has completed successfully. The application is deployed to Kubernetes."

  production-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: notify

    steps:
      - name: Deploy to Production
        run: |
          kubectl apply -f k8s/production-deployment.yaml --validate=false
          kubectl apply -f k8s/production-service.yaml --validate=false